schema_version: 1

context:
  name: amazon-textract-textractor
  version: "1.9.1"
  python_min: "3.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: e1ed95d4e0bfb685037e484da69c16ec5d09d1e6a1f3d1a163ee8d8aa1693206

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - textractor = textractor.cli.cli:textractor_cli

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - amazon-textract-caller >=0.2.4,<1
    - pillow
    - tabulate >=0.9,<0.10
    - xlsxwriter >=3.0,<4
    - editdistance >=0.6.2,<0.9

tests:
  - python:
      imports:
        - textractor
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A package to use AWS Textract services.
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  homepage: https://github.com/aws-samples/amazon-textract-textractor

extra:
  recipe-maintainers:
    - StevenSchaererQC
